### ISSUE TITLE
Javascript window.onload = function()

### ISSUE THREAD

**Issue by patonoide** [apusdigital/coaching#2]
Olá pessoal,

Estava trabalhando e reparei algo estranho quando usando window.onload.
Eu tinha o seguinte código

```
window.onload = function(){
     Code 1 
}

window.onload= function(){
      Code 2 
}

```
Os dois códigos faziam coisas diferentes porém apenas o segundo era executado, tentei atribuir um nome para cada mas mesmo assim apenas o segundo funcionava. No final juntei os dois códigos em uma função só. Gostaria de saber se só posso utilizar esse método de chamada apenas uma vez por página ou foi algo específico?

**Comment by mateusholzschuh** [comment]
O evento 'onload' é disparado ao final do carregamento do objeto, portanto ele somente é executado uma vez.

Ele espera a atribuição de uma função para ser executada ao final do carregamento do objeto em questão. No teu caso, somente executava a segunda função porque houve uma reatribuição (linha 5).

Uma solução tosca seria definir tuas funções, declarando cada uma em uma 'function' e chamar essas funções dentro do onload, tipo isso:

```

windows.onload = function() {
        f1();
        f2();
};

function f1() {
        /*Code 1*/
}

function f2() {
        /*Code 2*/
}

```

**Comment by patonoide** [comment]
Entendi o funcionamento, muito obrigado pela explicação. :)
