### ISSUE TITLE
Projeto Prático

### ISSUE THREAD

**Issue by diegomengarda** [apusdigital/coaching#3]
# Sistema de Cadastro de Produtos

## O sistema deve possuir o cadastro e gerenciamento das 3 entidades descritas abaixo, esse cadastro deve possuir telas com as operações de um CRUD:

- Tela de listagem com pesquisa e exclusão dos itens
- Tela de cadastro de novo ítem
- Tela de edição de um ítem

### Cadastro de Produtos
 - id
 - category_id
 - title
 - description
 - price
 - quantity

### Cadastro de Categorias de Produtos
 - id
 - name

### Estoque
 - id
 - product_id
 - quantity
 - date_time

## Como construir:
- O sistema deverá ser construído utilizando o AngularJS;
- A interface de UI fica de escolha do desenvolvedor;
- A API deve ser construída utiliando o json-server (https://github.com/typicode/json-server);
- Não é necessário utilizar login no sistema, mas pode ser implementado caso o desenvolvedor ache útil;
- Preferencialmente escrever código na língua inglesa;
- É apreciada a utilização do Gulp/Grunt, boas práticas, padrões de projeto, código comentado;

## Referências:
- https://code.tutsplus.com/pt/tutorials/fake-rest-api-up-and-running-using-json-server--cms-27871
- https://bulma.io/
- https://getbootstrap.com/
- https://material.io/develop/web/

**Comment by diegomengarda** [comment]
Pessoal, prazo final para entrega do projeto 02/07.

**Comment by KimberllyMoreles** [comment]
https://github.com/KimberllyMoreles/Stock-Managements

**Comment by mateusholzschuh** [comment]
[Apus - Project #1](https://github.com/mateusholzschuh/apus-p1)
